services:
  postgres:
    container_name: envify-psql
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=envify
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5342:5342

volumes:
  postgres-data:
    driver: local
